UPDATE --pALAVRA RESERVADA QUE ATUALIZA INFORMAÇÕES
LIVROS --NOSSA TABELAQUE SERÁ ATERADO A INFORMAÇÃO
SET -- SET INCIALIZA A PRIMEIRA ALTERAÇÃO A INFORMAÇÃO
Ativo = 0 -- EXPRESSÃO QUE VAI SER ALTERADA
WHERE Id= --PALAVRA QUE INICIALIZA AS CONDIÇÕES
(SELECT ID FROM Livros ORDER BY Id DESC OFFSET 1 ROWS FETCH NEXT 1 ROWS ONLY)